server:
  port: 8888

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8761/eureka
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://FIRST-SERVICE
        predicates:
        - Path=/employee/**
        
      - id: consumerModule
        uri: lb://SECOND-SERVICE
        predicates:
        - Path=/consumer/**

      - id: catalogAPI
        uri: lb://CATALOGAPI        
        predicates:
        - Path=/catalog/**        
        #you can now hit this api gateway via: http://localhost:8888/api1/abc

      - id: checkoutAPI
        uri: lb://CHECKOUTAPI
        predicates:
        - Path=/checkout/**
        #you can now hit endpoint like: http://localhost:8888/test1 this somehow maps to the minimal api endpoints

      - id: emailAPI
        uri: lb://EMAILAPI
        predicates:
        - Path=/email/**
        #you can now hit http://localhost:8888/api2